services:
  - type: web
    name: laufrennen-tracker
    runtime: node
    repo: https://github.com/gasserf97/laufrennen-tracker
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    plan: free
